

export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas ",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed answer/respone",
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top — making your learning more organize and structured",
  },
  {
    id: "04",
    title: 'Understand the "Why" Behind Answers',
    description:
      "Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each question",
  },
  {
    id: "05",
    title: 'Save, Organize, and Revisit',
    description:
     'Easily save your interview sets, organize them nesatly in your dashobard and pick up your preparation revisit',
  },
];